### ISSUE TITLE
Going through NPM's dispute procedure

### ISSUE THREAD

**Issue by aminya** [atom-ide-community/atom-languageclient#9]
Npm allows taking the name of the packages that are not updated for a long time. We should email the original developers, and if they do not give us access, npm will do so.
https://www.npmjs.com/policies/disputes

We should go through the procedure and take over the original package. This can be done in parallel with the improvements that are made here.

This is necessary because many IDE packages are relying on the old name. It is easier to get access to one package, instead of trying to update every single IDE package.

**Comment by UziTech** [comment]
I'll continue to get this package up to date but not release it until we get approval or rejection for the old name

**Comment by aminya** [comment]
> I'll continue to get this package up to date but not release it until we get approval or rejection for the old name

That's a good idea. Thanks!

**Comment by UziTech** [comment]
@aminya Did you email NPM about the dispute or is that something you wanted me to do?

**Comment by aminya** [comment]
No, I haven't done it. I think you can email them directly as you know more about the progress you have made. You should explain what changes we have done and we plan to do to. CC me on that email to keep me in the loop.

**Comment by UziTech** [comment]
I finally got around to sending the email to get the `atom-languageclient` name from npm. I got an email back saying one of the current owners daviwil@github.com is not a valid email so hopefully someone is actually getting the email at atom@github.com

**Comment by aminya** [comment]
Thank you, Tony! I got it. Let's see what they say.

**Comment by UziTech** [comment]
I had to resend it because I accidentally CC'd npm.com instead of npmjs.com

**Comment by aminya** [comment]
@UziTech It seems we have been waiting for 18 days, and so their time is finished. I think it is time to reply and ask npm directly to move the package.

**Comment by damieng** [comment]
As the original creator of atom-languageclient I have no objection however I did this while employed at GitHub so somebody there would need to be okay with this. I'll reach out to see if I can find who is appropriate as davidwil also left since then.

**Comment by damieng** [comment]
A few extra thoughts:

- You can @ people to notify them of a conversation. Email and dispute process would not have been my preference for this discussion.
- If package authors have pinned `atom-languageclient` versions (as was recommended) then taking over the package will not help.
- If they haven't pinned it then you'll need to be careful about breaking changes.

**Comment by aminya** [comment]
@damieng Thank you for your response. We really appreciate your help. 

> You can @ people to notify them of a conversation. Email and dispute process would not have been my preference for this discussion.

Personally, I have tried tagging people, opening issues, emailing personally, etc. many times, and often I have not gotten "any response". Fortunately, npm has this disputes procedure which allows us to continue working on a package even when the original authors don't. The situation is more awkward for `apm` packages. @atom / @github  do not provide such a procedure, and we have ended up making packages with new names. There is not even a way to mark another package as "deprecated". This is very unfortunate. As an example, "minimap" has 6 million users, which grow every day because it is always on the trending page. But to improve it, we had to start fresh, and our updated version which has only 1400 users! 

I hope @atom / @github do something about this lack of transferring old packages if they really care about Atom.

> If package authors have pinned atom-languageclient versions (as was recommended) then taking over the package will not help.
> If they haven't pinned it then you'll need to be careful about breaking changes.

For sure, we want to stay backward compatible. But if the package versions are pinned again, we face the "abandoned" package issue. There is no way to fix that. Unless GitHub/Atom provide us a method.

**Comment by damieng** [comment]
ide-csharp and ide-typescript at a quick glance are pinned to 0.9.9 - this was done because it had not hit 1.0.0 and so there were no semver guarantees yet.

I'd be *personally* up for transferring any GitHub/Atom owned ide-x repos over as well as the apm packages but again this is down to GitHub.com. As I lead the atom-ide project from conception through to my eventual departure I feel somewhat responsible and will see if I can find somebody who can authorize this to happen but can't promise anything.
